# Generated by Django 4.2 on 2023-05-01 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_user_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=uuid.uuid4, max_length=254, null=True, unique=True),
        ),
    ]
